/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rafirizqullah_2210010288_tb;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;

/**
 *
 * @author ACER
 */
public class FrameMasterSupplier extends javax.swing.JFrame {

    /**
     * Creates new form FrameMasterBarang
     */
    public FrameMasterSupplier() {
        initComponents();
        loadTableData();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSupplier = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNamaSupplier = new javax.swing.JTextField();
        jTextFieldEmailSupplier = new javax.swing.JTextField();
        jDateChooserTanggalBergabung = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextFieldAlamatSupplier = new javax.swing.JTextField();
        jTextFieldTeleponSupplier = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 500));

        jTableSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableSupplier.setPreferredSize(new java.awt.Dimension(500, 500));
        jTableSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSupplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSupplier);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        jPanel1.add(jScrollPane1, gridBagConstraints);

        jLabel1.setText("Nama Supplier");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Alamat Supplier");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Telepon Supplier");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Email Supplier");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Tanggal Bergabung");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(jLabel5, gridBagConstraints);

        jTextFieldNamaSupplier.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jTextFieldNamaSupplier, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jTextFieldEmailSupplier, gridBagConstraints);

        jDateChooserTanggalBergabung.setDate(new java.util.Date());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jDateChooserTanggalBergabung, gridBagConstraints);

        jButton1.setText("Buat Supplier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setText("Update Supplier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton3.setText("Hapus Supplier");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jPanel2, gridBagConstraints);

        jTextFieldAlamatSupplier.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jTextFieldAlamatSupplier, gridBagConstraints);

        jTextFieldTeleponSupplier.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jTextFieldTeleponSupplier, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // Ambil data dari form
            String namaSupplier = jTextFieldNamaSupplier.getText();
            String alamatSupplier = jTextFieldAlamatSupplier.getText();
            String teleponSupplier = jTextFieldTeleponSupplier.getText();
            String emailSupplier = jTextFieldEmailSupplier.getText();
            java.util.Date tanggalBergabung = jDateChooserTanggalBergabung.getDate();

            // Validasi input
            if (namaSupplier.isEmpty() || alamatSupplier.isEmpty() || teleponSupplier.isEmpty() || emailSupplier.isEmpty() || tanggalBergabung == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Harap lengkapi semua data!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Konversi tanggal ke java.sql.Date
            java.sql.Date sqlTanggalBergabung = new java.sql.Date(tanggalBergabung.getTime());

            // Simpan ke database
            try (Connection conn = DatabaseHelper.getConnection()) {
                String query = "INSERT INTO master_supplier (nama_supplier, alamat_supplier, telepon_supplier, email_supplier, tanggal_bergabung) VALUES (?, ?, ?, ?, ?)";
                try (PreparedStatement stmt = conn.prepareStatement(query)) {
                    stmt.setString(1, namaSupplier);
                    stmt.setString(2, alamatSupplier);
                    stmt.setString(3, teleponSupplier);
                    stmt.setString(4, emailSupplier);
                    stmt.setDate(5, sqlTanggalBergabung);

                    int rowsInserted = stmt.executeUpdate();
                    if (rowsInserted > 0) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Supplier berhasil dibuat!", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                        loadTableData();
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal membuat supplier: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // Ambil baris yang dipilih di JTable
            int selectedRow = jTableSupplier.getSelectedRow();
            if (selectedRow == -1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Pilih supplier yang ingin diupdate!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Ambil idSupplier dari JTable
            int idSupplier = (int) jTableSupplier.getValueAt(selectedRow, 0);

            // Ambil data dari form
            String namaSupplier = jTextFieldNamaSupplier.getText();
            String alamatSupplier = jTextFieldAlamatSupplier.getText();
            String teleponSupplier = jTextFieldTeleponSupplier.getText();
            String emailSupplier = jTextFieldEmailSupplier.getText();
            java.util.Date tanggalBergabung = jDateChooserTanggalBergabung.getDate();

            // Validasi input
            if (namaSupplier.isEmpty() || alamatSupplier.isEmpty() || teleponSupplier.isEmpty() || emailSupplier.isEmpty() || tanggalBergabung == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Harap lengkapi semua data!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Konversi tanggal ke java.sql.Date
            java.sql.Date sqlTanggalBergabung = new java.sql.Date(tanggalBergabung.getTime());

            // Update data di database
            try (Connection conn = DatabaseHelper.getConnection()) {
                String query = "UPDATE master_supplier SET nama_supplier = ?, alamat_supplier = ?, telepon_supplier = ?, email_supplier = ?, tanggal_bergabung = ? WHERE id_supplier = ?";
                try (PreparedStatement stmt = conn.prepareStatement(query)) {
                    stmt.setString(1, namaSupplier);
                    stmt.setString(2, alamatSupplier);
                    stmt.setString(3, teleponSupplier);
                    stmt.setString(4, emailSupplier);
                    stmt.setDate(5, sqlTanggalBergabung);
                    stmt.setInt(6, idSupplier);

                    int rowsUpdated = stmt.executeUpdate();
                    if (rowsUpdated > 0) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Supplier berhasil diupdate!", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                        loadTableData(); // Refresh tabel
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this, "Supplier tidak ditemukan atau gagal diupdate!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    }
                }
            }

            // Mengosongkan semua field input
            jTextFieldNamaSupplier.setText("");
            jTextFieldAlamatSupplier.setText("");
            jTextFieldTeleponSupplier.setText("");
            jTextFieldEmailSupplier.setText("");
            jDateChooserTanggalBergabung.setDate(null);

            // Menghapus selection di JTable
            jTableSupplier.clearSelection();
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal mengupdate supplier: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // Ambil baris yang dipilih di JTable
            int selectedRow = jTableSupplier.getSelectedRow();
            if (selectedRow == -1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Pilih supplier yang ingin dihapus!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Konfirmasi penghapusan
            int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus supplier ini?", "Konfirmasi", javax.swing.JOptionPane.YES_NO_OPTION);
            if (confirm != javax.swing.JOptionPane.YES_OPTION) {
                return;
            }

            // Ambil idSupplier dari JTable
            int idSupplier = (int) jTableSupplier.getValueAt(selectedRow, 0);

            // Hapus data dari database
            try (Connection conn = DatabaseHelper.getConnection()) {
                String query = "DELETE FROM master_supplier WHERE id_supplier = ?";
                try (PreparedStatement stmt = conn.prepareStatement(query)) {
                    stmt.setInt(1, idSupplier);

                    int rowsDeleted = stmt.executeUpdate();
                    if (rowsDeleted > 0) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Supplier berhasil dihapus!", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                        loadTableData(); // Refresh tabel
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this, "Supplier tidak ditemukan atau gagal dihapus!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    }
                }
            }

            // Mengosongkan semua field input
            jTextFieldNamaSupplier.setText("");
            jTextFieldAlamatSupplier.setText("");
            jTextFieldTeleponSupplier.setText("");
            jTextFieldEmailSupplier.setText("");
            jDateChooserTanggalBergabung.setDate(null);

            // Menghapus selection di JTable
            jTableSupplier.clearSelection();
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus supplier: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Mengosongkan semua field input
        jTextFieldNamaSupplier.setText("");
        jTextFieldAlamatSupplier.setText("");
        jTextFieldTeleponSupplier.setText("");
        jTextFieldEmailSupplier.setText("");
        jDateChooserTanggalBergabung.setDate(null);

        // Menghapus selection di JTable
        jTableSupplier.clearSelection();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTableSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSupplierMouseClicked
// Ambil baris yang dipilih
        int selectedRow = jTableSupplier.getSelectedRow();

        // Pastikan ada baris yang dipilih
        if (selectedRow != -1) {
            // Ambil data dari JTable dan set ke input form
            jTextFieldNamaSupplier.setText(jTableSupplier.getValueAt(selectedRow, 1).toString());
            jTextFieldAlamatSupplier.setText(jTableSupplier.getValueAt(selectedRow, 2).toString());
            jTextFieldTeleponSupplier.setText(jTableSupplier.getValueAt(selectedRow, 3).toString());
            jTextFieldEmailSupplier.setText(jTableSupplier.getValueAt(selectedRow, 4).toString());

            // Set tanggal bergabung (kolom ke-5 di tabel)
            java.sql.Date sqlDate = (java.sql.Date) jTableSupplier.getValueAt(selectedRow, 5);
            jDateChooserTanggalBergabung.setDate(sqlDate);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTableSupplierMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMasterSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMasterSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMasterSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMasterSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMasterSupplier().setVisible(true);
            }
        });
    }

    private void loadTableData() {
        try (Connection conn = DatabaseHelper.getConnection()) {
            String query = "SELECT * FROM master_supplier";
            try (Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery(query)) {
                ResultSetMetaData metaData = rs.getMetaData();
                int columnCount = metaData.getColumnCount();

                javax.swing.table.DefaultTableModel tableModel = new javax.swing.table.DefaultTableModel();

                for (int i = 1; i <= columnCount; i++) {
                    tableModel.addColumn(metaData.getColumnLabel(i));
                }

                while (rs.next()) {
                    Object[] row = new Object[columnCount];
                    for (int i = 0; i < columnCount; i++) {
                        row[i] = rs.getObject(i + 1);
                    }
                    tableModel.addRow(row);
                }

                jTableSupplier.setModel(tableModel);
            }
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooserTanggalBergabung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSupplier;
    private javax.swing.JTextField jTextFieldAlamatSupplier;
    private javax.swing.JTextField jTextFieldEmailSupplier;
    private javax.swing.JTextField jTextFieldNamaSupplier;
    private javax.swing.JTextField jTextFieldTeleponSupplier;
    // End of variables declaration//GEN-END:variables
}
